version: '3.8'

services:
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://db:27017/products

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://db:27017/orders
    depends_on:
      - product-service

  db:
    image: mongo:latest
    container_name: mongodbms
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
