
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY src/ .

# Expose port
EXPOSE 5002

# Start the server
CMD ["node", "server.js"]
