# Base image
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY src/ .

# Expose port
EXPOSE 5001

# Run the seed script and start the application
CMD ["sh", "-c", "node seed.js && npm start"]
